- hosts: localhost
  tasks:
  - name: ensure git is installed
    become: yes
    become_method: sudo
    yum: name=git state=latest
  - name: clone petclinic repo
    git: repo=https://github.com/roeiblack/spring-petclinic.git dest=~/petclinic
  - name: clone trep repo
    git: repo=https://github.com/roeiblack/trepo.git dest=~/trepo
